### ISSUE TITLE
Using overflow: hidden for .wrapper blocks Details of Query Params in page rest-api/users/list/

### ISSUE THREAD

**Issue by rogeriopradoj** [RocketChat/Rocket.Chat.Docs#852]
Page affected:

https://rocket.chat/docs/developer-guides/rest-api/users/list/

File that could be changed:

https://github.com/RocketChat/docs/blob/5faee06b1952c7cf7ec6f7f7de4bd5328af1149f/_sass/layout.scss#L152

Instead of:

```css
.wrapper {
    overflow: hidden
}
```

Could be used:
```css
.wrapper {
    overflow: auto
}
```

Evidence:

![image](https://user-images.githubusercontent.com/443391/43137702-e1982b82-8f22-11e8-975f-35fbbaacdb8c.png)
